[supervisord]
nodaemon=true
logfile=/var/log/supervisor/supervisord.log
pidfile=/tmp/supervisord.pid

[program:probotapi]
directory=/app
command=/usr/local/bin/gunicorn -w 2 -b 0.0.0.0:8000 probotapi.app:app
autostart=true
autorestart=true
startsecs=5
startretries=3
stdout_logfile=/var/log/gunicorn/stdout.log
stderr_logfile=/var/log/gunicorn/stderr.log
stopasgroup=true
killasgroup=true