[supervisord]
nodaemon=true
logfile=/var/log/supervisor/supervisord.log
pidfile=/tmp/supervisord.pid

[program:probotapi]
directory=/app
command=gunicorn --bind 0.0.0.0:8000 --workers 4 "probotapi.app:app"
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
stderr_logfile=/var/log/gunicorn/probotapi.err.log
stdout_logfile=/var/log/gunicorn/probotapi.out.log
stderr_logfile_maxbytes=10MB
stdout_logfile_maxbytes=10MB