[program:probotapi]
command=/home/ubuntu/programmable-web-project/venv/bin/gunicorn --bind 0.0.0.0:5000 --workers 4 "probotapi.app:app"
directory=/home/ubuntu/programmable-web-project
user=ubuntu
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
stderr_logfile=/var/log/probotapi/probotapi.err.log
stdout_logfile=/var/log/probotapi/probotapi.out.log